export type ServiceCategory = "Medical" | "Non-Medical";

export interface Service {
  id: string;
  slug: string;
  name: string;
  description: string;
  shortDescription: string;
  category: ServiceCategory;
  duration: string;
  intensity: "Gentle" | "Moderate" | "Intense";
  tags: string[];
  imageUrl?: string;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  slug: string;
  relatedTags: string[];
}

export const goals: Goal[] = [
  {
    id: "detox",
    title: "Detox & Reset",
    description: "e.g., Ozone Sauna, HOCATT, Lymphatic LET",
    slug: "detox-reset",
    relatedTags: ["Detox", "Cleanse", "Lymphatic", "Sauna"],
  },
  {
    id: "pain",
    title: "Pain Relief & Recovery",
    description: "e.g., Prolozone, Infrared Sauna",
    slug: "pain-relief",
    relatedTags: ["Pain", "Recovery", "Joints", "Muscle"],
  },
  {
    id: "energy",
    title: "Energy & Performance",
    description: "e.g., Vitamin IV, NAD+ Injections",
    slug: "energy-performance",
    relatedTags: ["Energy", "Brain", "Oxygen", "Performance"],
  },
  {
    id: "longevity",
    title: "Longevity & Optimization",
    description: "e.g., EBO2 Therapy, Ozone IV",
    slug: "longevity",
    relatedTags: ["Longevity", "Anti-aging", "Cellular"],
  },
  {
    id: "skin",
    title: "Skin & Aesthetics",
    description: "e.g., Microneedling, Exosomes, Plasma Pen",
    slug: "skin-aesthetics",
    relatedTags: ["Skin", "Beauty", "Face", "Collagen"],
  },
  {
    id: "weight",
    title: "Weight & Metabolic",
    description: "e.g., Weight Loss Injections",
    slug: "weight-metabolic",
    relatedTags: ["Weight Loss", "Metabolism", "Fat Loss"],
  },
];

export const services: Service[] = [
  // Clinic
  {
    id: "ozone-sauna",
    slug: "ozone-sauna-level-one",
    name: "Ozone Sauna (Level One)",
    shortDescription: "A gentle introduction to ozone therapy combined with steam.",
    description: "Experience the detoxifying power of ozone delivered through a comfortable steam sauna. This Level One therapy helps eliminate toxins, boost immunity, and improve circulation.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Moderate",
    tags: ["Detox", "Sauna", "Immunity", "Skin"],
  },
  {
    id: "hocatt",
    slug: "hocatt-sauna-level-two",
    name: "HOCATT Sauna (Level Two)",
    shortDescription: "The ultimate bio-chamber for detoxification and energy.",
    description: "HOCATT stands for Hyperthermic Ozone and Carbonic Acid Transdermal Technology. It delivers 10 modalities in one session for profound detoxification and cellular regeneration.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Intense",
    tags: ["Detox", "Sauna", "Energy", "Recovery", "Weight Loss"],
  },
  {
    id: "infrared",
    slug: "far-infrared-sauna",
    name: "Far Infrared Sauna",
    shortDescription: "Deep tissue heating for relaxation and sweat.",
    description: "Unlike traditional saunas, infrared heat penetrates deep into tissues to mobilize toxins, reduce inflammation, and promote deep relaxation.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Gentle",
    tags: ["Detox", "Relaxation", "Pain"],
  },
  {
    id: "theta",
    slug: "theta-chamber",
    name: "Theta Chamber",
    shortDescription: "Neurological balance and stress reduction.",
    description: "Using light, sound, and motion to induce a Theta brainwave state, helping to rewire neural pathways and reduce stress and anxiety.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Gentle",
    tags: ["Brain", "Mental Health", "Relaxation"],
  },
  {
    id: "lymph",
    slug: "lymphatic-let-therapy",
    name: "Lymphatic LET Therapy",
    shortDescription: "Targeted lymphatic drainage using light and energy.",
    description: "Lymphatic Enhancement Technology (LET) uses electronic and light energy to clear lymphatic congestion and improve fluid flow.",
    category: "Non-Medical",
    duration: "60 min",
    intensity: "Gentle",
    tags: ["Lymphatic", "Detox", "Recovery"],
  },
  {
    id: "flowpresso",
    slug: "flowpresso",
    name: "Flowpresso Lymphatic Compression",
    shortDescription: "3-in-1 sensory treatment for flow and relaxation.",
    description: "Combines compression, thermodynamic heat, and deep pressure to encourage lymph flow and calm the nervous system.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Gentle",
    tags: ["Lymphatic", "Relaxation", "Recovery"],
  },
  
  // Medical
  {
    id: "iv-vitamin",
    slug: "vitamin-iv-treatments",
    name: "Vitamin IV Treatments",
    shortDescription: "Direct nutrient infusion for maximum absorption.",
    description: "Customized IV drips to replenish hydration, vitamins, and minerals instantly, bypassing the digestive system.",
    category: "Medical",
    duration: "45-60 min",
    intensity: "Gentle",
    tags: ["Energy", "Immunity", "Hydration", "Recovery"],
  },
  {
    id: "iv-ozone",
    slug: "ozone-iv-treatments",
    name: "Ozone IV Treatments",
    shortDescription: "Systemic oxygenation and immune modulation.",
    description: "Medical-grade ozone therapy administered intravenously to combat pathogens and reduce systemic inflammation.",
    category: "Medical",
    duration: "60 min",
    intensity: "Moderate",
    tags: ["Immunity", "Detox", "Longevity"],
  },
  {
    id: "eb02",
    slug: "eb02-therapy",
    name: "EBO2 Therapy",
    shortDescription: "Advanced blood filtration and oxygenation.",
    description: "Extracorporeal Blood Oxygenation and Ozonation. A sophisticated filtration process that removes debris and oxygenates the blood.",
    category: "Medical",
    duration: "90 min",
    intensity: "Intense",
    tags: ["Longevity", "Detox", "Heart Health"],
  },
  {
    id: "weight-injections",
    slug: "weight-loss-injections",
    name: "Weight Loss Injections",
    shortDescription: "Medically supervised metabolic support.",
    description: "Targeted treatments to support metabolic health and assist with weight management goals.",
    category: "Medical",
    duration: "15 min",
    intensity: "Gentle",
    tags: ["Weight Loss", "Metabolism"],
  },

  // Aesthetics
  {
    id: "plasma-pen",
    slug: "plasma-skin-rejuvenation",
    name: "Plasma Skin Rejuvenation",
    shortDescription: "Non-surgical skin tightening and resurfacing.",
    description: "Uses plasma energy to tighten skin, reduce wrinkles, and improve texture without invasive surgery.",
    category: "Non-Medical",
    duration: "60 min",
    intensity: "Moderate",
    tags: ["Skin", "Anti-aging", "Beauty"],
  },
  {
    id: "microneedling",
    slug: "microneedling-treatments",
    name: "Microneedling",
    shortDescription: "Collagen induction therapy for smoother skin.",
    description: "Stimulates natural collagen production to treat scars, fine lines, and texture issues.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Moderate",
    tags: ["Skin", "Collagen", "Beauty"],
  },
  {
    id: "exosomes",
    slug: "exosome-treatments",
    name: "Exosome Treatments",
    shortDescription: "Cellular signaling for potent regeneration.",
    description: "Topical or injectable exosomes that signal your skin cells to repair and regenerate.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Gentle",
    tags: ["Skin", "Regeneration", "Anti-aging"],
  },

  // Regenerative
  {
    id: "prolozone",
    slug: "prolozone-pain-relief",
    name: "Prolozone Pain Relief",
    shortDescription: "Ozone injection therapy for joint pain.",
    description: "Combines ozone and nutrients injected into joints to reduce inflammation and stimulate healing.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Moderate",
    tags: ["Pain", "Joints", "Recovery"],
  },
  {
    id: "nad",
    slug: "nad-injection-program",
    name: "NAD+ Injection Program",
    shortDescription: "Cellular energy restoration.",
    description: "NAD+ is crucial for mitochondrial health. Injections help restore levels for better energy and cognitive function.",
    category: "Non-Medical",
    duration: "15 min",
    intensity: "Gentle",
    tags: ["Energy", "Brain", "Longevity"],
  },
  
  // Additional Medical Services
  {
    id: "vitamin-injections",
    slug: "vitamin-injections",
    name: "Vitamin Injections",
    shortDescription: "Quick nutrient boost for optimal health.",
    description: "Targeted intramuscular injections delivering essential vitamins and minerals directly into your system for quick absorption and immediate benefits.",
    category: "Medical",
    duration: "10 min",
    intensity: "Gentle",
    tags: ["Energy", "Immunity", "Recovery"],
  },
  {
    id: "peptide-injections",
    slug: "peptide-injections",
    name: "Peptide Injections",
    shortDescription: "Advanced cellular signaling molecules.",
    description: "Targeted peptide therapies designed to naturally stimulate cellular repair, promote anti-aging, enhance recovery, and optimize overall metabolic function.",
    category: "Medical",
    duration: "15 min",
    intensity: "Gentle",
    tags: ["Anti-aging", "Recovery", "Weight Loss", "Longevity"],
  },
  {
    id: "luma-elite-iv",
    slug: "luma-elite-iv",
    name: "Luma Elite IV",
    shortDescription: "Our premier comprehensive IV therapy.",
    description: "The ultimate intravenous cocktail loaded with premium vitamins, minerals, and antioxidants to profoundly revitalize, hydrate, and support immune function.",
    category: "Medical",
    duration: "60 min",
    intensity: "Moderate",
    tags: ["Energy", "Immunity", "Detox", "Longevity"],
  },
  {
    id: "functional-medical-testing",
    slug: "functional-medical-testing",
    name: "Functional Medical Testing",
    shortDescription: "Comprehensive biomarker and health analysis.",
    description: "In-depth functional lab testing to identify root causes of symptoms, uncover nutritional deficiencies, and guide your personalized wellness protocol.",
    category: "Medical",
    duration: "30 min",
    intensity: "Gentle",
    tags: ["Testing", "Wellness", "Detox"],
  },
  {
    id: "curewave-laser",
    slug: "curewave-laser-treatments",
    name: "Curewave Laser Treatments",
    shortDescription: "Advanced laser therapy for pain relief.",
    description: "Cutting-edge laser technology that penetrates deep into tissues to reduce inflammation, accelerate cellular repair, and provide effective pain relief.",
    category: "Medical",
    duration: "30 min",
    intensity: "Gentle",
    tags: ["Pain", "Recovery", "Joints"],
  },
  {
    id: "methylene-blue",
    slug: "methylene-blue",
    name: "Methylene Blue",
    shortDescription: "Mitochondrial optimization and brain health.",
    description: "A potent cognitive enhancer and metabolic optimizer that supports mitochondrial function, increases cellular energy, and provides neuroprotective benefits.",
    category: "Medical",
    duration: "45 min",
    intensity: "Gentle",
    tags: ["Brain", "Energy", "Longevity"],
  },

  // Additional Aesthetics & Regenerative (Non-Medical)
  {
    id: "ez-gel",
    slug: "ez-gel",
    name: "EZ Gel",
    shortDescription: "100% natural, regenerative bio-filler.",
    description: "An innovative, all-natural autologous filler made from your own blood proteins and growth factors to restore volume and rejuvenate the skin.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Moderate",
    tags: ["Skin", "Beauty", "Anti-aging", "Regeneration"],
  },
  {
    id: "collagen-stimulation",
    slug: "collagen-stimulation-treatments",
    name: "Collagen Stimulation",
    shortDescription: "Treatments to boost natural collagen.",
    description: "Targeted therapies designed to trigger your body's natural collagen production, resulting in firmer, smoother, and more youthful-looking skin.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Moderate",
    tags: ["Skin", "Beauty", "Anti-aging"],
  },
  {
    id: "glutathione",
    slug: "glutathione",
    name: "Glutathione Treatments",
    shortDescription: "The master antioxidant for skin and detox.",
    description: "Powerful antioxidant therapies that promote cellular detoxification, boost immune function, and provide a radiant, glowing complexion.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Gentle",
    tags: ["Skin", "Detox", "Immunity", "Beauty"],
  },
  {
    id: "fillers-botox",
    slug: "fillers",
    name: "Botox & Fillers",
    shortDescription: "Expert injectable aesthetic treatments.",
    description: "Expertly administered neurotoxins and dermal fillers to smooth wrinkles, restore lost volume, and beautifully enhance your natural facial contours.",
    category: "Non-Medical",
    duration: "30 min",
    intensity: "Moderate",
    tags: ["Skin", "Beauty", "Anti-aging"],
  },
  {
    id: "red-light-therapy",
    slug: "red-light-therapy",
    name: "Red Light & Skin Rejuvenation",
    shortDescription: "Photobiomodulation for cellular health.",
    description: "Clinically proven red and near-infrared light therapy to reduce inflammation, accelerate healing, and stimulate collagen production for healthier skin.",
    category: "Non-Medical",
    duration: "20 min",
    intensity: "Gentle",
    tags: ["Skin", "Recovery", "Energy", "Anti-aging"],
  },
  {
    id: "hair-restoration",
    slug: "hair-restoration",
    name: "Hair Restoration",
    shortDescription: "Natural regeneration for thicker, fuller hair.",
    description: "Personalized treatments utilizing regenerative techniques to stimulate dormant hair follicles and naturally enhance hair growth and thickness.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Moderate",
    tags: ["Hair", "Beauty", "Regeneration"],
  },
  {
    id: "joint-regeneration",
    slug: "joint-regeneration",
    name: "Joint Regeneration",
    shortDescription: "Advanced therapies for joint health.",
    description: "Comprehensive regenerative treatments aimed at repairing damaged cartilage, reducing chronic joint pain, and restoring optimal mobility.",
    category: "Non-Medical",
    duration: "45 min",
    intensity: "Moderate",
    tags: ["Pain", "Joints", "Recovery", "Regeneration"],
  },
  {
    id: "v-sel-cellular",
    slug: "v-sel-cellular-regeneration",
    name: "V-SEL Cellular Regeneration",
    shortDescription: "Cutting-edge stem cell therapy.",
    description: "Very Small Embryonic-Like (V-SEL) stem cell treatments utilizing your body's own potent regenerative cells to repair tissues and promote profound healing.",
    category: "Non-Medical",
    duration: "60 min",
    intensity: "Moderate",
    tags: ["Regeneration", "Longevity", "Healing"],
  },
];
